## ---- include = FALSE---------------------------------------------------------
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)

## ---- eval = FALSE------------------------------------------------------------
#  # forthcoming, not sure about the full repo tree
#  # meanwhile, clone the repo and `Install and Restart`
#  # or `devtools::load_all()`
#  remotes::install_bitbucket(repo = "monkeytronics/r-analytics", subdir = "monkeytronics.reports")

## -----------------------------------------------------------------------------
library(monkeytronics.reports2)

## -----------------------------------------------------------------------------
test_params()

## -----------------------------------------------------------------------------
# wrangled_devices <- wrangle_devices(test_params()$filtered_devices)
# wrangled_weather <- wrangle_weather(
#  filtered_weather = test_params()$filtered_weather,
#  from_timestamp = test_params()$fromTimeStamp,
#  to_timestamp = test_params()$toTimeStamp
# )
# wrangled_obs <- wrangle_observations(
#  filtered_obs = test_params()$filtered_obs,
#  from_timestamp = test_params()$fromTimeStamp,
#  to_timestamp = test_params()$toTimeStamp,
#  devices = wrangled_devices,
#  weather = wrangled_weather
#)
# data_volume <- get_data_volume(
#  observations = wrangled_obs,
#  from_timestamp = test_params()$fromTimeStamp,
#  to_timestamp = test_params()$toTimeStamp
#  )
# wrangled_devices <- remove_excluded_devices(
#  target_data = wrangled_devices,
#  data_volume = data_volume
# )
# wrangled_obs <- remove_excluded_devices(
#  target_data = wrangled_obs,
#  data_volume = data_volume
# )

## -----------------------------------------------------------------------------
# monkey_palettes(devices = wrangled_devices)
# set_options(observations = wrangled_obs)

## -----------------------------------------------------------------------------
# ts_chart(
#   observations = wrangled_obs,
#  from_timestamp = test_params()$fromTimeStamp,
#  to_timestamp = test_params()$toTimeStamp,
#  target_variable = "hum"
# )

## -----------------------------------------------------------------------------
# ts_chart(
#  observations = wrangled_obs,
#  from_timestamp = test_params()$fromTimeStamp,
#  to_timestamp = test_params()$toTimeStamp,
#  target_variable = "temp"
# )

## ---- eval = FALSE------------------------------------------------------------
#  # the system.file calls are to access the example data installed with the package
#  # in production, the list of parameters will be generated by the script calling this
#  # report
#  
#  obs  <- system.file("data/filtered_obs.csv", package = "monkeytronics.reports")
#  dev  <- system.file("data/filtered_devices.csv", package = "monkeytronics.reports")
#  wea  <- system.file("data/filtered_weather.csv", package = "monkeytronics.reports")
#  int  <- system.file("data/filtered_interventions.csv", package = "monkeytronics.reports")
#  from <- 1627639151
#  to   <- 1630317551
#  
#  par_list <- make_params_list(
#    filtered_obs = obs,
#    filtered_devices = dev,
#    filtered_weather = wea,
#    filtered_interventions = int,
#    fromTimeStamp = from,
#    toTimeStamp = to
#  )
#  
#  # knit with default file name and output dir
#  # knit_home_report(par_list)

